"""
train_distill.py — Train the GNN to mimic the existing weighted-sum agent.

Loads distill_data.pt generated by generate_distill_data.py,
trains BoardGNN to predict the same scores, saves gnn_weights.pt.

Usage:
    python3 train_distill.py

Output:
    gnn_weights.pt — trained GNN weights, ready for agent_gnn.py
"""

import random
import time
import torch
import torch.nn as nn
import torch.optim as optim

from network import BoardGNN, save_model

from network import DEVICE
print(f"Training on {DEVICE}")

# -------------------------
# CONFIG
# -------------------------

DATA_FILE       = 'distill_data.pt'
OUTPUT_FILE     = 'gnn_weights.pt'
VAL_FRACTION    = 0.1       # fraction of data held out for validation
MAX_SAMPLES     = 2000      # set to None to use all data; 2000 for quick POC
EPOCHS          = 10        # increase to 50 for full training
LR              = 1e-3
LR_DECAY        = 0.5       # multiply LR by this when val loss plateaus
PATIENCE        = 5         # epochs without improvement before LR decay
MIN_LR          = 1e-5      # stop decaying below this
SEED            = 42

# Score normalisation: divide targets by this so scores are in ~[-1, 1] range.
# Typical mid-game scores are in [-500, 500], so 500 is a reasonable scale.
# The GNN output will be in normalised units; we denormalise when using it
# for move selection in agent_gnn.py.
SCORE_SCALE     = 500.0


# -------------------------
# TRAINING LOOP
# -------------------------

def train():
    random.seed(SEED)
    torch.manual_seed(SEED)

    # Load data
    print(f"Loading data from {DATA_FILE}...")
    all_samples = torch.load(DATA_FILE)
    print(f"  {len(all_samples)} samples loaded")

    # Optionally truncate for quick POC
    if MAX_SAMPLES is not None and len(all_samples) > MAX_SAMPLES:
        all_samples = all_samples[:MAX_SAMPLES]
        print(f"  truncated to {MAX_SAMPLES} samples (MAX_SAMPLES)")

    # Train / val split (data is pre-shuffled by generate_distill_data.py)
    n_val   = max(1, int(len(all_samples) * VAL_FRACTION))
    n_train = len(all_samples) - n_val
    train_data = all_samples[:n_train]
    val_data   = all_samples[n_train:]
    print(f"  {n_train} train, {n_val} val")

    # Normalise scores
    train_scores = torch.tensor([s for _, s in train_data])
    print(f"\nTraining score stats (before normalisation):")
    print(f"  mean={train_scores.mean():.2f}  std={train_scores.std():.2f}  "
          f"min={train_scores.min():.2f}  max={train_scores.max():.2f}")

    # Model, optimizer, loss
    model     = BoardGNN().to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=LR)
    criterion = nn.MSELoss()
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='min', factor=LR_DECAY,
        patience=PATIENCE, min_lr=MIN_LR, verbose=False)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"\nModel: {total_params:,} parameters")
    print(f"Training for {EPOCHS} epochs...\n")

    best_val_loss  = float('inf')
    best_epoch     = 0

    for epoch in range(1, EPOCHS + 1):
        epoch_start = time.time()

        # --- TRAIN ---
        model.train()
        random.shuffle(train_data)
        train_loss_sum = 0.0

        for encoded, score in train_data:
            target = torch.tensor(score / SCORE_SCALE).to(DEVICE)

            optimizer.zero_grad()
            pred   = model(encoded)
            loss   = criterion(pred, target)
            loss.backward()
            optimizer.step()

            train_loss_sum += loss.item()

        train_loss = train_loss_sum / len(train_data)

        # --- VALIDATE ---
        model.eval()
        val_loss_sum = 0.0

        with torch.no_grad():
            for encoded, score in val_data:
                target = torch.tensor(score / SCORE_SCALE).to(DEVICE)
                pred   = model(encoded)
                loss   = criterion(pred, target)
                val_loss_sum += loss.item()

        val_loss = val_loss_sum / len(val_data)

        # LR scheduling based on val loss
        scheduler.step(val_loss)

        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch    = epoch
            save_model(model, OUTPUT_FILE)
            marker = " ← best"
        else:
            marker = ""

        epoch_time = time.time() - epoch_start
        current_lr = optimizer.param_groups[0]['lr']
        print(f"Epoch {epoch:3d}/{EPOCHS}  "
              f"train={train_loss:.4f}  val={val_loss:.4f}  "
              f"lr={current_lr:.2e}  {epoch_time:.1f}s{marker}")

        # Early stopping if LR has decayed to minimum
        if current_lr <= MIN_LR and epoch > best_epoch + PATIENCE * 2:
            print(f"\nEarly stopping: LR at minimum and no improvement for "
                  f"{epoch - best_epoch} epochs")
            break

    print(f"\nBest val loss: {best_val_loss:.4f} at epoch {best_epoch}")
    print(f"Model saved to {OUTPUT_FILE}")
    print(f"\nNote: scores are normalised by SCORE_SCALE={SCORE_SCALE}")
    print(f"      agent_gnn.py must multiply GNN output by {SCORE_SCALE} "
          f"to get comparable scores")


if __name__ == '__main__':
    train()
